workflows:
  ios-release:
    name: "📱 iOS Release - TestFlight & App Store"
    max_build_duration: 120
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

      groups:
        # Créez ce groupe dans Codemagic avec vos variables
        - app_store_credentials

      vars:
        # Informations de base
        BUNDLE_ID: "com.snipermarketacademy.snipermarketacademy"
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"

      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.snipermarketacademy.snipermarketacademy

    scripts:
      - name: "🔐 Configuration du code signing"
        script: |
          set -e
          echo "Configuration des certificats et provisioning profiles..."
          xcode-project use-profiles

      - name: "🧹 Nettoyage et préparation"
        script: |
          set -e
          echo "Nettoyage de l'environnement Flutter..."
          flutter clean
          flutter pub get

      - name: "📦 Installation des dépendances iOS"
        script: |
          set -e
          cd ios
          rm -rf Pods Podfile.lock .symlinks
          pod install --repo-update
          cd ..

      - name: "🔍 Vérification de la configuration"
        script: |
          flutter doctor -v
          cd ios && xcodebuild -list -workspace Runner.xcworkspace && cd ..

      - name: "🏗️ Build de l'application iOS"
        script: |
          set -e
          set -x
          
          BUILD_NUMBER=$(($(date +%s)))
          
          flutter build ipa \
            --release \
            --export-options-plist=ios/ExportOptions.plist \
            --build-name=1.0.0 \
            --build-number=$BUILD_NUMBER

      - name: "✅ Vérification de l'IPA"
        script: |
          if [ -f build/ios/ipa/*.ipa ]; then
            echo "✅ IPA généré avec succès"
            ls -lh build/ios/ipa/*.ipa
          else
            echo "❌ Erreur: IPA non trouvé"
            exit 1
          fi

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log

    publishing:
      email:
        recipients:
          - capron.kevin@hotmail.fr
        notify:
          success: true
          failure: true

      app_store_connect:
        auth:
          key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
          issuer_id: $APP_STORE_CONNECT_ISSUER_ID
          key: $APP_STORE_CONNECT_PRIVATE_KEY

        submit_to_testflight: true
        beta_groups:
          - Internal Testers

        # Décommentez pour soumettre à l'App Store
        # submit_to_app_store: true