name: sniper_market_academy
description: Application éducative ICT/SMC pour traders - 100% offline
publish_to: 'none'

version: 2.0.0+1

environment:
  sdk: '>=3.8.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # État et navigation
  provider: ^6.1.2
  
  # Stockage local (offline)
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.3
  path_provider: ^2.1.3
  
  # Graphiques et charts
  candlesticks: ^2.1.0
  fl_chart: ^0.68.0
  syncfusion_flutter_charts: ^26.2.14
  
  # UI/UX
  lottie: ^3.1.2
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  
  # Utilitaires
  intl: ^0.19.0
  uuid: ^4.4.2
  
  # Audio
  audioplayers: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.11
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"

flutter:
  uses-material-design: true
  
  assets:
    # Images principales
    - assets/images/
    - assets/images/icon.png
    - assets/images/logo_sniper.png
    - assets/images/menu_background.png
    - assets/images/bg_chart.png
    - assets/images/placeholder.png
    
    # Modules explicatifs
    - assets/images/modules/
    - assets/images/modules/market_structure_explained.png
    - assets/images/modules/bos_module_explained.png
    - assets/images/modules/fvg_module_explained.png
    - assets/images/modules/ote_module_explained.png
    - assets/images/modules/liquidity_module_explained.png
    - assets/images/modules/displacement_module_explained.png
    - assets/images/modules/orderblock_module_explained.png
    
    # Exercices interactifs
    - assets/images/exercises/
    - assets/images/exercises/bos_question_graph_1.png
    - assets/images/exercises/bos_question_graph_2.png
    - assets/images/exercises/fvg_exercise1_graph.png
    - assets/images/exercises/ote_exercise1_graph.png
    - assets/images/exercises/displacement_exercise1_graph.png
    - assets/images/exercises/liquidity_exercise1_graph.png
    - assets/images/exercises/orderblock_exercise1_graph.png
    - assets/images/exercises/setup_complet_exercise1_graph.png
    - assets/images/exercises/setup_complet_exercise2_graph.png
    - assets/images/exercises/fvg_example.png
    
    # Simulateur
    - assets/images/charts/
    - assets/images/charts/chart_1.png
    - assets/images/charts/chart_2.png
    - assets/images/charts/chart_3.png
    - assets/images/charts/chart_4.png
    
    # Animations
    - assets/animations/
    - assets/animations/candles.json
    
    # Sons
    - assets/audio/
    - assets/audio/sniper_scan_effect.mp3
    
    # Données JSON (contenu offline)
    - assets/data/
    - assets/data/modules.json
    - assets/data/exercises.json
    - assets/data/glossary.json
