// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArBJY2EdSR20rd8FpuTthWMZulF-5it1g',
    appId: '1:895034541399:web:c21104213331b010f76a12',
    messagingSenderId: '895034541399',
    projectId: 'snipermarketacademy',
    authDomain: 'snipermarketacademy.firebaseapp.com',
    storageBucket: 'snipermarketacademy.firebasestorage.app',
    measurementId: 'G-2D2BKSJV6W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrBXhKoy9LyvjZ6AX1bwp1LdA7r6TSJxc',
    appId: '1:895034541399:android:ef572381d18d132bf76a12',
    messagingSenderId: '895034541399',
    projectId: 'snipermarketacademy',
    storageBucket: 'snipermarketacademy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWZQE845Amwc0YoYfrnOMu6k-uoefU4ks',
    appId: '1:895034541399:ios:a658e1bf7470b00ff76a12',
    messagingSenderId: '895034541399',
    projectId: 'snipermarketacademy',
    storageBucket: 'snipermarketacademy.firebasestorage.app',
    iosBundleId: 'com.example.sniperFixedClean',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWZQE845Amwc0YoYfrnOMu6k-uoefU4ks',
    appId: '1:895034541399:ios:a658e1bf7470b00ff76a12',
    messagingSenderId: '895034541399',
    projectId: 'snipermarketacademy',
    storageBucket: 'snipermarketacademy.firebasestorage.app',
    iosBundleId: 'com.example.sniperFixedClean',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArBJY2EdSR20rd8FpuTthWMZulF-5it1g',
    appId: '1:895034541399:web:58f6a92b4a0ca280f76a12',
    messagingSenderId: '895034541399',
    projectId: 'snipermarketacademy',
    authDomain: 'snipermarketacademy.firebaseapp.com',
    storageBucket: 'snipermarketacademy.firebasestorage.app',
    measurementId: 'G-GNBVEJPNR3',
  );
}
