# Plateforme minimale (Cloud Firestore & audioplayers exigent iOS 13+)
platform :ios, '13.0'

# Obligatoire pour audioplayers_darwin
use_frameworks! :linkage => :dynamic
use_modular_headers!

# Empêche les conflits entre les pods
install! 'cocoapods',
         :deterministic_uuids => false

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_application_path = '../'
  eval(File.read(File.join(flutter_application_path, '.flutter-plugins-dependencies')), binding)
end

# ✅ Corrige parfois des erreurs de compilation liées aux headers
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
